# Docker Compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this Docker Compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker compose pull'.
# - Run 'docker compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    networks:
      - paperless
    volumes:
      - /home/say/paperless-data/redisdata:/data

  db:
    image: docker.io/library/postgres:17
    restart: unless-stopped
    networks:
      - paperless
    volumes:
      - /home/say/paperless-data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    user: 1000
    restart: unless-stopped
    depends_on:
      - db
      - broker
    networks:
      - paperless
    ports:
      - "8000:8000"
    volumes:
      - /mnt/storage-box/paperless/data:/usr/src/paperless/data
      - /mnt/storage-box/paperless/media:/usr/src/paperless/media
      - /mnt/storage-box/paperless/export:/usr/src/paperless/export
      - /mnt/storage-box/paperless/consume:/usr/src/paperless/consume
    env_file: podman-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379  # Replace with actual broker IP
      PAPERLESS_DBHOST: db              # Replace with actual db IP

networks:
  paperless:
    driver: bridge
