name: "Notify"
on:
  workflow_dispatch:
  push:

jobs:
  notify:
    name: "Notify"
    runs-on: ubuntu-latest
    steps:
      - name: Install Curl
        run: sudo apt-get install -y curl
      - name: Trigger GitOps deploy webhook
        env:
          WEBHOOK_SECRET: ${{ secrets.GITOPS_WEBHOOK_SECRET }}
        run: |
          SIGNATURE=$(printf '' | openssl dgst -sha256 -hmac "$WEBHOOK_SECRET" | cut -d ' ' -f2)
          
          # Send POST request to webhook
          curl -X POST https://gitops.say.software/deploy-all-changed \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature-256: sha256=$SIGNATURE" \
            -H "X-GitHub-Event: push"
